Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -14,32 +14,36 @@ permissions:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v3
+    - name: Checkout repository
+      uses: actions/checkout@v2
+
     - name: Set up Python 3.10
       uses: actions/setup-python@v3
       with:
         python-version: "3.10"
+
     - name: Install dependencies
       run: |
+        set -e
         python -m pip install --upgrade pip
         pip install flake8 pytest
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+
     - name: Lint with flake8
       run: |
-        # stop the build if there are Python syntax errors or undefined names
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
-        
+
     - name: Test with pytest
       id: test
       run: |
         set -e
-        pytest main.py -vv || echo "Tests failed" >> test_results.txt
+        pytest main.py -vv || echo "Tests failed" >> $GITHUB_WORKSPACE/test_results.txt
+      env:
+        GITHUB_WORKSPACE: ${{ github.workspace }}
 
   post:
     needs: build
@@ -49,7 +53,7 @@ jobs:
       uses: actions/checkout@v2
 
     - name: Check test results
-      run: cat test_results.txt
+      run: cat $GITHUB_WORKSPACE/test_results.txt
       id: check_test_results
 
     - name: Publish to README.txt on failure
